# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HTEffectExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
#  pod 'HTEffect', :path => '../'
  pod 'HTEffect'
  pod 'Masonry'
  pod 'SSZipArchive'
  
  
  
  
  # Pods for HTEffectExample

end
